[package]
name = "game-fps"
version = "0.1.1"
build = "build.rs"
edition = "2021"
description = "North Star FPS game composition dynamically loaded through the canonical plugin ABI"
license = "Proprietary"

[package.metadata.northstar.provider]
route = "engine.game.module.fps"
install_name = "fps-game"
implements = "engine.game.module"

[lib]
crate-type = ["cdylib"]

[dependencies]
abi_stable = { workspace = true }
newengine-plugin-api = { workspace = true }
serde_json = { workspace = true }
newengine-game-module-fps = { workspace = true }
newengine-game-ready-profile = { workspace = true }
newengine-project-api = { workspace = true }

[build-dependencies]
embed-resource = "3.0.6"
